## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import random

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [187]:
array = np.random.randint(0, 10, size=(1, 10))
print(array)

def change_sign(array):
    array[(3 < array) & (array < 8)] *= -1
    return array

print(change_sign(array))

[[7 3 1 4 4 7 1 6 7 8]]
[[-7  3  1 -4 -4 -7  1 -6 -7  8]]


**2.** Заменить максимальный элемент случайного массива на 0

In [205]:
array = np.random.random(10)
print(array)

def change_max(array):
    array[array == max(array)] = 0
    return array

print(change_max(array))

[0.2482622  0.83876524 0.82730975 0.62658656 0.54996653 0.30976326
 0.06245944 0.10079549 0.55055883 0.13235521]
[0.2482622  0.         0.82730975 0.62658656 0.54996653 0.30976326
 0.06245944 0.10079549 0.55055883 0.13235521]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [104]:
a = np.random.randint(0, 10, size = (3, 3))


def direct_prod(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(a, direct_prod(a), sep='\n\n', end='\n\n')

[[6 2 8]
 [0 2 9]
 [9 5 1]]

[[6 0 9]
 [6 0 5]
 [6 0 1]
 [6 2 9]
 [6 2 5]
 [6 2 1]
 [6 9 9]
 [6 9 5]
 [6 9 1]
 [2 0 9]
 [2 0 5]
 [2 0 1]
 [2 2 9]
 [2 2 5]
 [2 2 1]
 [2 9 9]
 [2 9 5]
 [2 9 1]
 [8 0 9]
 [8 0 5]
 [8 0 1]
 [8 2 9]
 [8 2 5]
 [8 2 1]
 [8 9 9]
 [8 9 5]
 [8 9 1]]



**4**. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(A)
print(B)
print(rows)

[[3 0 0]
 [3 3 4]
 [1 0 2]
 [0 2 2]
 [0 1 0]
 [0 1 2]
 [2 2 0]
 [0 1 3]]
[[3 2]
 [1 1]]
[1 2 3 4 5 6 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
matrix = np.random.randint(0, 5, size = (10, 3))
print(matrix)

E = np.logical_and.reduce(matrix[:,1:] == matrix[:,:-1], axis=1)
print(E)
U = matrix[~E]
print(U)

[[1 0 1]
 [1 2 4]
 [3 0 0]
 [1 1 0]
 [1 4 1]
 [2 4 3]
 [3 3 4]
 [1 0 0]
 [0 2 0]
 [0 3 3]]
[False False False False False False False False False False]
[[1 0 1]
 [1 2 4]
 [3 0 0]
 [1 1 0]
 [1 4 1]
 [2 4 3]
 [3 3 4]
 [1 0 0]
 [0 2 0]
 [0 3 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [204]:
# a = np.random.randint(0, 10, size = (3, 3))
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [3, 4, 5],
              [3, 4, 5],
              [3, 4, 6],
              [2, 3, 4]])

def delete_recurring_string(data):
    return np.unique(data, axis = 0)

print(delete_recurring_string(a))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [3 4 6]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [189]:
# Numpy
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diag = np.diagonal(X)
print(f'Numpy: {np.prod(diag[diag>0])}')


# Python
Y = X.tolist()

def product(matrix):
    product = 1
    for i, row in enumerate(matrix):
        try:
            if row[i] != 0:
                product *= row[i]
        except IndexError:
            pass
    
        
        
    return product

print(f'Python: {product(Y)}')

        

Numpy: 3
Python: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [71]:
# Numpy
x = np.sort(np.array([1, 2, 2, 4]))
y = np.sort(np.array([4, 2, 1, 2]))
print((x == y).all())

# Python
from collections import Counter
x = Counter(x.tolist())
y = Counter(y.tolist())
print(x == y)


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [64]:
# Numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print(x[1:][zero[:-1]].max())

# Python
x = x.tolist()
print(max(x[i] for i in range(1, len(x)) if not x[i-1]))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [11]:
# Numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
unique, counts = np.unique(x, return_counts=True)
print(unique, counts)


# Python
from collections import Counter
x = Counter(np.array([2, 2, 2, 3, 3, 3, 5]).tolist())
nums = [i for i in x.keys()]
repeat = [i for i in x.values()]
print(nums, repeat)

[2 3 5] [3 3 1]
[2, 3, 5] [3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [198]:
# Numpy

simple_point = [3, 4]
points = np.arange(20).reshape(10, 2)

def numpy_euclidian_dist(v1, v2):
    return np.sqrt(np.sum((v1 - v2)**2, axis=1))

print(numpy_euclidian_dist(points, simple_point))

# Python
from math import sqrt
points = points.tolist()

def python_euclidian_dist(points, y):
    return [sqrt(sum(map(lambda p: (p[0]-p[1])**2, zip(point, y)))) for point in points]
    
    
print(python_euclidian_dist(points, simple_point))

[ 4.24264069  1.41421356  1.41421356  4.24264069  7.07106781  9.89949494
 12.72792206 15.55634919 18.38477631 21.21320344]
[4.242640687119285, 1.4142135623730951, 1.4142135623730951, 4.242640687119285, 7.0710678118654755, 9.899494936611665, 12.727922061357855, 15.556349186104045, 18.384776310850235, 21.213203435596427]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [13]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [14]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [32]:
average_calories = np.average(calorie_stats) - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [199]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [200]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [201]:
nth_percentile = np.percentile(calorie_stats, np.arange(101)).min()
nth_percentile

50.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [202]:
more_calories = calorie_stats[calorie_stats > 60].size / calorie_stats.size * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [203]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [21]:
# your code